package:
    name: nrel-rex
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - click
    - h5py==2.9
    - numpy>=1.16
    - pandas
    - psutil
    - scipy
    - toml
  run:
    - python
    - pip
    - click
    - h5py==2.9
    - {{ pin_compatible('numpy') }}
    - pandas
    - psutil
    - scipy
    - toml
  run-constrained:
    - h5pyd

about:
  home: "https://github.com/NREL/rex"
  license: BSD 3-Clause
  summary: "REsource eXtraction (rex) tool"
  doc_url: "https://nrel.github.io/rex"
  dev_url: "https://github.com/NREL/rex"
