name: reV Pytests

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout rex
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
        path: rex
    - name: checkout reV
      uses: actions/checkout@v2
      with:
        repository: nrel/reV
        fetch-depth: 1
        path: rev
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd rex
        python -m pip install .
        cd ..
        cd rev
        python -m pip install .
    - name: Run reV pytest
      run: |
        python -m pip install pytest
        python -m pytest -v
