name: reVX Pytests

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout rex
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
        path: rex
    - name: checkout reVX
      uses: actions/checkout@v2
      with:
        repository: nrel/reVX
        fetch-depth: 1
        path: reVX
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Install rex dependencies
      working-directory: ./rex
      shell: bash -l {0}
      run: |
        conda install pip
        pip install -e .
    - name: Install reVX dependencies
      working-directory: ./reVX
      shell: bash -l {0}
      run: |
        conda install rtree
        pip install -e .
    - name: Run reVX pytest
      working-directory: ./reVX
      shell: bash -l {0}
      run: |
        conda install pytest
        pytest -v
